/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Harris Chou
 * Date: August 22, 2023
 * Final Project Select Shop portion
 */
public class frmSelectShop extends javax.swing.JFrame {

    /**
     * Creates new form frmSelectShop
     */
    public frmSelectShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnClothingShop = new javax.swing.JToggleButton();
        btnMacaroonsShop = new javax.swing.JToggleButton();
        btnSkincareShop = new javax.swing.JToggleButton();
        btnTechnologyShop = new javax.swing.JToggleButton();
        lblClothingShop = new javax.swing.JLabel();
        lblMacaroonShop = new javax.swing.JLabel();
        lblSkinCareShop = new javax.swing.JLabel();
        lblTechnologyShop = new javax.swing.JLabel();
        lblSentence = new javax.swing.JLabel();
        btnClose = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Welcome to Harris's Business");

        btnClothingShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T-Shirt.jpg"))); // NOI18N
        btnClothingShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothingShopActionPerformed(evt);
            }
        });

        btnMacaroonsShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Macaroons.jpg"))); // NOI18N
        btnMacaroonsShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacaroonsShopActionPerformed(evt);
            }
        });

        btnSkincareShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Skin Care.jpg"))); // NOI18N
        btnSkincareShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkincareShopActionPerformed(evt);
            }
        });

        btnTechnologyShop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gaming Setup.jpg"))); // NOI18N
        btnTechnologyShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechnologyShopActionPerformed(evt);
            }
        });

        lblClothingShop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClothingShop.setText("Clothing Shop");

        lblMacaroonShop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMacaroonShop.setText("Macaroons Shop");

        lblSkinCareShop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSkinCareShop.setText("Skincare Shop");

        lblTechnologyShop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTechnologyShop.setText("Technology Shop");

        lblSentence.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSentence.setText("Please Click on a Shop to Begin!");

        btnClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClose.setText("Close Program");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSkincareShop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClothingShop, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTechnologyShop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMacaroonsShop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(lblSkinCareShop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTechnologyShop)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lblClothingShop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMacaroonShop)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnClose)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblSentence)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSentence)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClothingShop)
                    .addComponent(lblMacaroonShop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClothingShop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMacaroonsShop, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkinCareShop)
                    .addComponent(lblTechnologyShop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTechnologyShop, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkincareShop, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClothingShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothingShopActionPerformed
        new frmClothingShop().setVisible(true);//This will open the frmClothingShop GUI
        this.dispose();//This will close the frmSelectShop GUI
    }//GEN-LAST:event_btnClothingShopActionPerformed

    private void btnSkincareShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkincareShopActionPerformed
        new frmSkinCareShop().setVisible(true);//This will open the frmSkinCareShop GUI
        this.dispose();//This will close the frmSelectShop GUI
    }//GEN-LAST:event_btnSkincareShopActionPerformed

    private void btnMacaroonsShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacaroonsShopActionPerformed
        new frmMacaroonsShop().setVisible(true);//This will open the frmMacaroonsShop GUI
        this.dispose();//This will close the frmSelectShop GUI
    }//GEN-LAST:event_btnMacaroonsShopActionPerformed

    private void btnTechnologyShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechnologyShopActionPerformed
        new frmTechnologyShop().setVisible(true);//This will open the frmTechnologyShop GUI
        this.dispose();//This will close the frmSelectShop GUI
    }//GEN-LAST:event_btnTechnologyShopActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();//This will close the frmSelectShop GUI and end the program
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSelectShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSelectShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSelectShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSelectShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelectShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnClose;
    private javax.swing.JToggleButton btnClothingShop;
    private javax.swing.JToggleButton btnMacaroonsShop;
    private javax.swing.JToggleButton btnSkincareShop;
    private javax.swing.JToggleButton btnTechnologyShop;
    private javax.swing.JLabel lblClothingShop;
    private javax.swing.JLabel lblMacaroonShop;
    private javax.swing.JLabel lblSentence;
    private javax.swing.JLabel lblSkinCareShop;
    private javax.swing.JLabel lblTechnologyShop;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
