/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Harris Chou
 * Date: August 22, 2023
 * Final Project Technology Shop portion
 */
import java.text.DecimalFormat;//importing the decimalformat
public class frmTechnologyShop extends javax.swing.JFrame 
{
    
    //Declaring the DecimalFormat for two decmial places
    DecimalFormat df2 = new DecimalFormat ("0.00"); 
    //Declaring the final tax constant to store it

    /**
     * Creates new form frmTechnologyShop
     */
    public frmTechnologyShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblMouse = new javax.swing.JLabel();
        lblKeyboard = new javax.swing.JLabel();
        lblHeadset = new javax.swing.JLabel();
        lblMic = new javax.swing.JLabel();
        lblMousepad = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        txtMouse = new javax.swing.JTextField();
        txtKeyboard = new javax.swing.JTextField();
        txtHeadset = new javax.swing.JTextField();
        txtMic = new javax.swing.JTextField();
        txtMousepad = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JToggleButton();
        btnGoBack = new javax.swing.JToggleButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Technology Shop");

        lblMouse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMouse.setText("Gaming Mouse ($51.99):");

        lblKeyboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKeyboard.setText("Gaming Keyboard ($80.99):");

        lblHeadset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHeadset.setText("Gaming Headset ($150.99):");

        lblMic.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMic.setText("Gaming Mic ($234.99):");

        lblMousepad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMousepad.setText("Mousepad ($42.99):");

        lblTaxes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTaxes.setText("Taxes (13%):");

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtotal.setText("Subtotal:");

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrandTotal.setText("Grand Total:");

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gaming Setup.jpg"))); // NOI18N

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnGoBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGoBack.setText("Back To Menu");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblError.setText("Please enter the quantity of items u would like to purchase");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnGoBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)))
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btnCalculate))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKeyboard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHeadset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMousepad)
                                            .addComponent(lblMouse)))
                                    .addComponent(lblHeadset)
                                    .addComponent(lblMic, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMousepad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMic, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTaxes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnGoBack))
                .addGap(15, 15, 15)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMousepad)
                    .addComponent(txtMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaxes))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMouse)
                    .addComponent(txtKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txtHeadset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKeyboard))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeadset)
                            .addComponent(txtMic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMic)
                    .addComponent(txtMousepad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrandTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculate)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        new frmSelectShop().setVisible(true);//This will open the frmSelectShop GUI
        this.dispose();//This will close the frmTechnologyShop GUI
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
    //Declare Variables for each item
    int intNum1 = 0;
    int intNum2 = 0;
    int intNum3 = 0;
    int intNum4 = 0;
    int intNum5 = 0;
    double answer;
    final double dblTaxes = 0.13;//Declaring the final tax constant to store it

    try 
    {
        //Receive the values from each item if the fields are not empty
        if (!txtMousepad.getText().isEmpty())//if mousepad textbox is empty 
        {
            intNum1 = Integer.parseInt(txtMousepad.getText());//intNum1 will equal to 0
        }
        if (!txtMouse.getText().isEmpty())//if mouse textbox is empty
        {
            intNum2 = Integer.parseInt(txtMouse.getText());//intNum2 will equal to 0
        }
        if (!txtKeyboard.getText().isEmpty())//of keyboard textbox is empty
        {
            intNum3 = Integer.parseInt(txtKeyboard.getText());//intNum3 will equal to 0
        }
        if (!txtHeadset.getText().isEmpty())//if headset textbox is empty
        {
            intNum4 = Integer.parseInt(txtHeadset.getText());//intNum4 will equal to 0
        }
        if (!txtMic.getText().isEmpty())//if mic textbox is empty
        {
            intNum5 = Integer.parseInt(txtMic.getText());//intNum5 will equal to 0
        }

        //Check for negative numbers
        if (intNum1 < 0 || intNum2 < 0 || intNum3 < 0 || intNum4 < 0 || intNum5 < 0) 
        {
            lblError.setText("Please do not include negative numbers!");
            //Reset input fields and labels after negative numbers checked
            txtMousepad.setText("");
            txtMouse.setText("");
            txtKeyboard.setText("");
            txtHeadset.setText("");
            txtMic.setText("");
            return;//Return the negative numbers
        }

        //Calculation for the Subtotal
        answer = (intNum1 * 42.99) + (intNum2 * 51.99) + (intNum3 * 80.99) + (intNum4 * 150.99) + (intNum5 * 234.99);

        // Display the Subtotal
        lblSubtotal.setText("Subtotal: $" + df2.format(answer));
        //Calculating the tax from the subtotal
        double dblTax = answer * dblTaxes;
        lblTaxes.setText("Taxes(13%): $" + df2.format(dblTax));
        //Calculating the GrandTotal by adding both the answer and dblTax
        lblGrandTotal.setText("Grand Total: $" + df2.format(answer + dblTax));
        
        //Reset input fields and labels after calculation
        txtMousepad.setText("");
        txtMouse.setText("");
        txtKeyboard.setText("");
        txtHeadset.setText("");
        txtMic.setText("");
        lblError.setText("");
        
    } catch (NumberFormatException e) 
    {
        //Let them know not to add anything other than numbers
        lblError.setText("Don't add anything other than numbers!");
        //Handle the exception outputting no value
        lblSubtotal.setText("Subtotal: $0.00");
        lblTaxes.setText("Taxes(13%): $0.00");
        lblGrandTotal.setText("Grand Total: $0.00");
        //Reset input fields and labels after NumberFormatError
        txtMousepad.setText("");
        txtMouse.setText("");
        txtKeyboard.setText("");
        txtHeadset.setText("");
        txtMic.setText("");
        
    }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTechnologyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTechnologyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTechnologyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTechnologyShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTechnologyShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalculate;
    private javax.swing.JToggleButton btnGoBack;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblHeadset;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblKeyboard;
    private javax.swing.JLabel lblMic;
    private javax.swing.JLabel lblMouse;
    private javax.swing.JLabel lblMousepad;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtHeadset;
    private javax.swing.JTextField txtKeyboard;
    private javax.swing.JTextField txtMic;
    private javax.swing.JTextField txtMouse;
    private javax.swing.JTextField txtMousepad;
    // End of variables declaration//GEN-END:variables
}
